services:
  nginx-web:
    container_name: web
    build: ./web
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/labsat.cpa.unicamp.br.chained.pem:/etc/nginx/ssl/labsat.cpa.unicamp.br.pem
      - /etc/ssl/private/labsat.cpa.unicamp.br.key:/etc/nginx/ssl/labsat.cpa.unicamp.br.key
      - /dates:/usr/share/nginx/html/dates

  nginx-tiles:
    container_name: tiles
    build: ./nginx
    ports:
      - "4000:4000"
    volumes:
      - /etc/ssl/labsat.cpa.unicamp.br.chained.pem:/etc/nginx/ssl/labsat.cpa.unicamp.br.pem
      - /etc/ssl/private/labsat.cpa.unicamp.br.key:/etc/nginx/ssl/labsat.cpa.unicamp.br.key
      - /var/products:/usr/share/nginx/html
